DROP VIEW IF EXISTS v_car_rent_summary;
DROP TABLE IF EXISTS Применение_скидки CASCADE;
DROP TABLE IF EXISTS Штраф CASCADE;
DROP TABLE IF EXISTS Скидка CASCADE;
DROP TABLE IF EXISTS Сделка CASCADE;
DROP TABLE IF EXISTS Автомобиль CASCADE;
DROP TABLE IF EXISTS Клиент CASCADE;
