@startuml
entity Клиент
entity Автомобиль
entity Сделка
entity Скидка
entity Штраф
entity Применение_скидки
Клиент ||--o{ Сделка
Автомобиль ||--o{ Сделка
Сделка ||--o{ Штраф
Сделка ||--o{ Применение_скидки
Скидка ||--o{ Применение_скидки
@enduml
